services:
  app:
    image: registry.hilkiano.com/quench-be:latest
    container_name: quench-be
    restart: unless-stopped
    working_dir: /var/www

    env_file:
      - .env

    volumes:
      - .env:/var/www/.env:ro

    ports:
      - "127.0.0.1:9000:9000"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - quench-net

networks:
  quench-net:
    driver: bridge
