services:
  app:
    image: registry.hilkiano.com/quench-be:latest
    container_name: quench-be
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - quench-net

networks:
  quench-net:
    driver: bridge
